// https://stackoverflow.com/a/78418162
// https://www.reddit.com/r/nextjs/comments/18zcgkd/comment/kghp5el/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth, signIn, signOut } from "@/auth";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!session?.user && (
            <form
            action={async () => {
              "use server"
              await signIn("discord");
            }}
          >
            <button type="submit">Sign in</button>
          </form>
          )}
          {session?.user && (
                      <form
                      action={async () => {
                        "use server"
                        await signOut();
                      }}
                    >
                      {session.user.image && <span><img alt="profile" width="40" height="40" src={session.user.image}/></span>}
                      <button type="submit">Sign out</button>
                    </form>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
